### ISSUE TITLE
Cannot compile with Apple LLVM version 6.0

### ISSUE THREAD

**Issue by tbago** [tbago/base#1]
error message:
In file included from ./strings/string_number_conversions.cc:5:
../base/strings/string_number_conversions.h:121:23: error: implicit instantiation of undefined template
      'std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
    std::stringstream stream;
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1/iosfwd:83:11: note: 
      template is declared here
    class basic_stringstream;
          ^
In file included from ./strings/string_number_conversions.cc:5:
../base/strings/string_number_conversions.h:131:24: error: implicit instantiation of undefined template
      'std::basic_stringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >'
    std::wstringstream stream;
